FROM python:3.9-slim-bookworm

WORKDIR /app

# Secure: update packages & clean cache
RUN apt-get update && apt-get upgrade -y && apt-get clean && rm -rf /var/lib/apt/lists/*

COPY . .

RUN pip install --no-cache-dir -r requirements.txt || true

EXPOSE 5000
