@echo off

echo Starting the Learning part Backends...

echo Starting Step By Step Approach backend (Node.js)...
start cmd /k "cd template\stepbystep\backend && npm install && node server.js"

echo Starting Classification Approach backend (Node.js)...
start cmd /k "cd template\code_classification_template\backend && npm install && node server.js"

echo Starting Diagram based Approach backend (Node.js)...
start cmd /k "cd template\Diagram-based-learning\Server && npm install && node server.js"

echo Starting Chart based Approach backend (Python)...
start cmd /k "cd template\chart && python app.py"

echo Starting Map based Approach backend (Python)...
start cmd /k "cd template\map_template && python app.py"

echo Starting the Game part Backends...

echo Starting Memory Matching Game backend (Node.js)...
start cmd /k "cd template\memory_matching_game && npm install && node backend.js"

echo Starting Ordering Game backend (Node.js)...
start cmd /k "cd Ordering_game\order-steps-backend && npm install && node server.js"

echo Starting Drag and Drop Game backend (Node.js)...
start cmd /k "cd drag_and_drop && npm install && node server.js"

echo Starting Maze Game backend (Python)...
start cmd /k "cd maze_Game1 && python app.py"

echo Starting Save_the_char (Python)...
start cmd /k "cd Save_the_char && python app.py"

echo Starting Frog Game backend (Python)...
start cmd /k "cd frog_game && python app.py"

echo Starting rocket_game (Python)...
start cmd /k "cd rocket_game && python app.py"

echo Starting Phase1-Game1 (Python)...
start cmd /k "cd FYP_phase1_fullcode\Game2\Game1\Server && python new_app.py"

echo Starting Phase1-Game2-Gemini-GPT (Python)...
start cmd /k "cd FYP_phase1_fullcode\Game2\Game2-Evaluation\finetuningGpt2\backend && python gemini_gpt2_flask.py"

echo Starting Phase1-Game2-mcq_app (Python)...
start cmd /k "cd FYP_phase1_fullcode\Game2\Game2-Evaluation\mcq_app\backend && python app.py"

echo Starting Phase1-Game2-backend (Node.js)...
start cmd /k "cd FYP_phase1_fullcode\Game2\backend && npm install && node server.js"

echo.
echo All servers launched in separate CMD windows.
pause